# Generated by Django 5.2.1 on 2025-06-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootandMouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reference', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cattle_density', models.IntegerField()),
                ('rainfall', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('adjacent_national_parks', models.FloatField(max_length=4)),
                ('international_boarder', models.FloatField(max_length=4)),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
